### PR TITLE
Proof Statistics 

### PR DESCRIPTION
**Pull request by dd4g12**
Document Generator with proof statistics

### CODE REVIEW

**Review by cfsnook — CHANGES_REQUESTED** [review]
please use compatible version ranges for all dependencies
remove unused imports in 2 source files
build.properties should include OSGI-INF/ in bin build

**Comment by cfsnook** [comment]
Questions...
I think this is specific to iUML-B not Event-B? should we change the bundle name to iUML-B Document Generator? 

We also need feature and sdk to publish it.

**Comment by dd4g12** [comment]
Thanks Colin, I addressed your comments.

**Comment by cfsnook** [comment]
Thanks, however, a few more points arise:

please add a branding plugin (copy the one from classdiagrams and change the about and plugin properties

reference the new branding plugin in the feature.xml (see first page of feature editor)

remove the following licence clause from  feature.xml (in feature AND in sdk ):
   <license url="http://www.example.com/license">
      [Enter License Description here.]
   </license>

in sdk feature.xml, also set up feature description and feature copyright and licence so that it is the same as the feature feature.xml

the sdk feature.xml should not  include any plug-ins

the sdk feature.xml should  include these 2 features:
ac.soton.eventb.documentor.feature,
ac.soton.eventb.documentor.source.feature

The sdk build.properties should start by building the source feature. I.E. the first 2 lines should be:
individualSourceBundles=true
generate.feature@ac.soton.eventb.documentor.source.feature=ac.soton.eventb..documentor.feature

**Comment by dd4g12** [comment]
Sorry this is the first time I do it :)
I have updated the plugins as suggested, but I still have a warning in the sdk plugin  feature reference id="ac.soton.eventb.documentor.source.feature" cannot be resolved. I updated the build properties but is there anything else I missed?

**Comment by cfsnook** [comment]
No worries.. it is ok to make mistakes on your first time.. next time I am sure it will be perfect at first review ;-)

It is normal to have the warning for "id="ac.soton.eventb.documentor.source.feature" cannot be resolved" (because the source feature is generated automatically during build)
 
However,  the branding plugin has a few problems
it is missing a folder `icons'  containing the IUMLB.png icon 
the about.ini  should have the following entry to reference the icon:
 <hash> Property "featureImage" contains path to feature image (32x32)
 featureImage=icons/IUMLB.png

Also there is a missing \n\ at the end of the first line of aboutText in about.properties

**Comment by dd4g12** [comment]
Done, sorry I removed icon but actually make since to keep it since iwe change it to  iUML-B document generator.

**Comment by cfsnook** [comment]
The icon is the most important thing in branding ;-) 
You need to add the branding plugin to the included plugins (in the feature.xml) with unpack ticked. I  noticed that you have set the version number for the other plugin.. it is best to leave it at 0.0.0 so that the feature will build with any version. Hence the plugins section in feature.xml should look like this:

` <plugin
        id="ac.soton.eventb.documentor" 
        download-size="0"
        install-size="0"
        version="0.0.0"
        unpack="false"/>`

 `   <plugin
         id="ac.soton.eventb.documentor.branding"
         download-size="0"
         install-size="0"
         version="0.0.0"/>`




I also noticed a spelling mistake in the feature properties: "stateistics" sb "statistics"

**Comment by dd4g12** [comment]
fingers crossed this time :)

**Review by cfsnook — APPROVED** [review]

**Pull request merged**
