### PR TITLE
feature histories to common format

### PR DESCRIPTION
**Pull request by cfsnook**
slight reformatting of feature histories to match other released plugins

### CODE REVIEW

**Comment by tshoang** [comment]
@cfsnook , @dd4g12 : Do we need a separate update site for this?

**Comment by cfsnook** [comment]
> @cfsnook , @dd4g12 : Do we need a separate update site for this?

No we don't, It was just for testing but we can also use the prototypes on blog for that.
Shall i remove the update site from the git repo?

I am about to put the release on Rodin update site.

**Comment by tshoang** [comment]
@cfsnook I think you should remove it from this repo as it is unnecessary. I thought you want @dd4g12 to release it on the Rodin Update Site. There are the instructions somewhere ...

**Review by dd4g12 — APPROVED** [review]
Thanks

**Pull request merged**
